/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace agile
{
    public sealed class imCounter_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public short imageNumber;
 
        public imCounter_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x2857e7716b28d536L;
 
        static imCounter_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("agile.imCounter_t"))
                return 0L;
 
            classes.Add("agile.imCounter_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.utime); 
 
            outs.Write(this.imageNumber); 
 
        }
 
        public imCounter_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public imCounter_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static agile.imCounter_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            agile.imCounter_t o = new agile.imCounter_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.utime = ins.ReadInt64();
 
            this.imageNumber = ins.ReadInt16();
 
        }
 
        public agile.imCounter_t Copy()
        {
            agile.imCounter_t outobj = new agile.imCounter_t();
            outobj.utime = this.utime;
 
            outobj.imageNumber = this.imageNumber;
 
            return outobj;
        }
    }
}

