/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace agile
{
    public sealed class motorsWsRef_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public double[] wsRef;
 
        public motorsWsRef_t()
        {
            wsRef = new double[4];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x49c5737cc1aa6b60L;
 
        static motorsWsRef_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("agile.motorsWsRef_t"))
                return 0L;
 
            classes.Add("agile.motorsWsRef_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.utime); 
 
            for (int a = 0; a < 4; a++) {
                outs.Write(this.wsRef[a]); 
            }
 
        }
 
        public motorsWsRef_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public motorsWsRef_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static agile.motorsWsRef_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            agile.motorsWsRef_t o = new agile.motorsWsRef_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.utime = ins.ReadInt64();
 
            this.wsRef = new double[(int) 4];
            for (int a = 0; a < 4; a++) {
                this.wsRef[a] = ins.ReadDouble();
            }
 
        }
 
        public agile.motorsWsRef_t Copy()
        {
            agile.motorsWsRef_t outobj = new agile.motorsWsRef_t();
            outobj.utime = this.utime;
 
            outobj.wsRef = new double[(int) 4];
            for (int a = 0; a < 4; a++) {
                outobj.wsRef[a] = this.wsRef[a];
            }
 
            return outobj;
        }
    }
}

