/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace agile
{
    public sealed class obstacles_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public short numObs;
        public double[,] obsLocation;
        public double[] obsRadius;
 
        public obstacles_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x74c19f90f5617809L;
 
        static obstacles_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("agile.obstacles_t"))
                return 0L;
 
            classes.Add("agile.obstacles_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.utime); 
 
            outs.Write(this.numObs); 
 
            for (int a = 0; a < this.numObs; a++) {
                for (int b = 0; b < 2; b++) {
                    outs.Write(this.obsLocation[a,b]); 
                }
            }
 
            for (int a = 0; a < this.numObs; a++) {
                outs.Write(this.obsRadius[a]); 
            }
 
        }
 
        public obstacles_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public obstacles_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static agile.obstacles_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            agile.obstacles_t o = new agile.obstacles_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.utime = ins.ReadInt64();
 
            this.numObs = ins.ReadInt16();
 
            this.obsLocation = new double[(int) numObs,(int) 2];
            for (int a = 0; a < this.numObs; a++) {
                for (int b = 0; b < 2; b++) {
                    this.obsLocation[a,b] = ins.ReadDouble();
                }
            }
 
            this.obsRadius = new double[(int) numObs];
            for (int a = 0; a < this.numObs; a++) {
                this.obsRadius[a] = ins.ReadDouble();
            }
 
        }
 
        public agile.obstacles_t Copy()
        {
            agile.obstacles_t outobj = new agile.obstacles_t();
            outobj.utime = this.utime;
 
            outobj.numObs = this.numObs;
 
            outobj.obsLocation = new double[(int) numObs,(int) 2];
            for (int a = 0; a < this.numObs; a++) {
                for (int b = 0; b < 2; b++) {
                    outobj.obsLocation[a,b] = this.obsLocation[a,b];
                }
            }
 
            outobj.obsRadius = new double[(int) numObs];
            for (int a = 0; a < this.numObs; a++) {
                outobj.obsRadius[a] = this.obsRadius[a];
            }
 
            return outobj;
        }
    }
}

