/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace agile
{
    public sealed class poseRef_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public double[] position;
        public double[] orientEuler;
 
        public poseRef_t()
        {
            position = new double[3];
            orientEuler = new double[3];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x9423567d5826db97L;
 
        static poseRef_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("agile.poseRef_t"))
                return 0L;
 
            classes.Add("agile.poseRef_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.utime); 
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.position[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.orientEuler[a]); 
            }
 
        }
 
        public poseRef_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public poseRef_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static agile.poseRef_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            agile.poseRef_t o = new agile.poseRef_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.utime = ins.ReadInt64();
 
            this.position = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.position[a] = ins.ReadDouble();
            }
 
            this.orientEuler = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.orientEuler[a] = ins.ReadDouble();
            }
 
        }
 
        public agile.poseRef_t Copy()
        {
            agile.poseRef_t outobj = new agile.poseRef_t();
            outobj.utime = this.utime;
 
            outobj.position = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.position[a] = this.position[a];
            }
 
            outobj.orientEuler = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.orientEuler[a] = this.orientEuler[a];
            }
 
            return outobj;
        }
    }
}

