/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace agile
{
    public sealed class pose_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public long timestampDevice;
        public double[] position;
        public double[] orient;
        public double[,] variances;
 
        public pose_t()
        {
            position = new double[3];
            orient = new double[4];
            variances = new double[6,6];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xb4f86b701179c1abL;
 
        static pose_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("agile.pose_t"))
                return 0L;
 
            classes.Add("agile.pose_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.utime); 
 
            outs.Write(this.timestampDevice); 
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.position[a]); 
            }
 
            for (int a = 0; a < 4; a++) {
                outs.Write(this.orient[a]); 
            }
 
            for (int a = 0; a < 6; a++) {
                for (int b = 0; b < 6; b++) {
                    outs.Write(this.variances[a,b]); 
                }
            }
 
        }
 
        public pose_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public pose_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static agile.pose_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            agile.pose_t o = new agile.pose_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.utime = ins.ReadInt64();
 
            this.timestampDevice = ins.ReadInt64();
 
            this.position = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.position[a] = ins.ReadDouble();
            }
 
            this.orient = new double[(int) 4];
            for (int a = 0; a < 4; a++) {
                this.orient[a] = ins.ReadDouble();
            }
 
            this.variances = new double[(int) 6,(int) 6];
            for (int a = 0; a < 6; a++) {
                for (int b = 0; b < 6; b++) {
                    this.variances[a,b] = ins.ReadDouble();
                }
            }
 
        }
 
        public agile.pose_t Copy()
        {
            agile.pose_t outobj = new agile.pose_t();
            outobj.utime = this.utime;
 
            outobj.timestampDevice = this.timestampDevice;
 
            outobj.position = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.position[a] = this.position[a];
            }
 
            outobj.orient = new double[(int) 4];
            for (int a = 0; a < 4; a++) {
                outobj.orient[a] = this.orient[a];
            }
 
            outobj.variances = new double[(int) 6,(int) 6];
            for (int a = 0; a < 6; a++) {
                for (int b = 0; b < 6; b++) {
                    outobj.variances[a,b] = this.variances[a,b];
                }
            }
 
            return outobj;
        }
    }
}

