/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace agile
{
    public sealed class statusPod_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public String podName;
        public short status;
 
        public statusPod_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x39709896264bdd62L;
 
        static statusPod_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("agile.statusPod_t"))
                return 0L;
 
            classes.Add("agile.statusPod_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            outs.Write(this.utime); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.podName); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            outs.Write(this.status); 
 
        }
 
        public statusPod_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public statusPod_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static agile.statusPod_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            agile.statusPod_t o = new agile.statusPod_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.utime = ins.ReadInt64();
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.podName = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.status = ins.ReadInt16();
 
        }
 
        public agile.statusPod_t Copy()
        {
            agile.statusPod_t outobj = new agile.statusPod_t();
            outobj.utime = this.utime;
 
            outobj.podName = this.podName;
 
            outobj.status = this.status;
 
            return outobj;
        }
    }
}

