/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace agile
{
    public sealed class tags_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public long timestampCamera;
        public int featuresNrFound;
        public short[] featureId;
        public double[,] featLoc;
        public double[,] featLocVar;
        public double[,] featDirEuler;
        public double[,] featDirEulerVar;
 
        public tags_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x582cfb2b02892422L;
 
        static tags_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("agile.tags_t"))
                return 0L;
 
            classes.Add("agile.tags_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.utime); 
 
            outs.Write(this.timestampCamera); 
 
            outs.Write(this.featuresNrFound); 
 
            for (int a = 0; a < this.featuresNrFound; a++) {
                outs.Write(this.featureId[a]); 
            }
 
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 3; b++) {
                    outs.Write(this.featLoc[a,b]); 
                }
            }
 
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 9; b++) {
                    outs.Write(this.featLocVar[a,b]); 
                }
            }
 
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 3; b++) {
                    outs.Write(this.featDirEuler[a,b]); 
                }
            }
 
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 9; b++) {
                    outs.Write(this.featDirEulerVar[a,b]); 
                }
            }
 
        }
 
        public tags_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public tags_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static agile.tags_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            agile.tags_t o = new agile.tags_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.utime = ins.ReadInt64();
 
            this.timestampCamera = ins.ReadInt64();
 
            this.featuresNrFound = ins.ReadInt32();
 
            this.featureId = new short[(int) featuresNrFound];
            for (int a = 0; a < this.featuresNrFound; a++) {
                this.featureId[a] = ins.ReadInt16();
            }
 
            this.featLoc = new double[(int) featuresNrFound,(int) 3];
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 3; b++) {
                    this.featLoc[a,b] = ins.ReadDouble();
                }
            }
 
            this.featLocVar = new double[(int) featuresNrFound,(int) 9];
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 9; b++) {
                    this.featLocVar[a,b] = ins.ReadDouble();
                }
            }
 
            this.featDirEuler = new double[(int) featuresNrFound,(int) 3];
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 3; b++) {
                    this.featDirEuler[a,b] = ins.ReadDouble();
                }
            }
 
            this.featDirEulerVar = new double[(int) featuresNrFound,(int) 9];
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 9; b++) {
                    this.featDirEulerVar[a,b] = ins.ReadDouble();
                }
            }
 
        }
 
        public agile.tags_t Copy()
        {
            agile.tags_t outobj = new agile.tags_t();
            outobj.utime = this.utime;
 
            outobj.timestampCamera = this.timestampCamera;
 
            outobj.featuresNrFound = this.featuresNrFound;
 
            outobj.featureId = new short[(int) featuresNrFound];
            for (int a = 0; a < this.featuresNrFound; a++) {
                outobj.featureId[a] = this.featureId[a];
            }
 
            outobj.featLoc = new double[(int) featuresNrFound,(int) 3];
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 3; b++) {
                    outobj.featLoc[a,b] = this.featLoc[a,b];
                }
            }
 
            outobj.featLocVar = new double[(int) featuresNrFound,(int) 9];
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 9; b++) {
                    outobj.featLocVar[a,b] = this.featLocVar[a,b];
                }
            }
 
            outobj.featDirEuler = new double[(int) featuresNrFound,(int) 3];
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 3; b++) {
                    outobj.featDirEuler[a,b] = this.featDirEuler[a,b];
                }
            }
 
            outobj.featDirEulerVar = new double[(int) featuresNrFound,(int) 9];
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 9; b++) {
                    outobj.featDirEulerVar[a,b] = this.featDirEulerVar[a,b];
                }
            }
 
            return outobj;
        }
    }
}

