/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace agile
{
    public sealed class triangulation_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public long timestampCamera;
        public short featuresNrFound;
        public short[] featureId;
        public short[] numKeys;
        public double[] maxReprojError;
        public double[] meanReprojError;
        public double[] whitenedError;
        public double[,] rankValue;
        public double[,] featureLocation;
        public double[,] featureLocationVariances;
 
        public triangulation_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x6031a37570183d9cL;
 
        static triangulation_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("agile.triangulation_t"))
                return 0L;
 
            classes.Add("agile.triangulation_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.utime); 
 
            outs.Write(this.timestampCamera); 
 
            outs.Write(this.featuresNrFound); 
 
            for (int a = 0; a < this.featuresNrFound; a++) {
                outs.Write(this.featureId[a]); 
            }
 
            for (int a = 0; a < this.featuresNrFound; a++) {
                outs.Write(this.numKeys[a]); 
            }
 
            for (int a = 0; a < this.featuresNrFound; a++) {
                outs.Write(this.maxReprojError[a]); 
            }
 
            for (int a = 0; a < this.featuresNrFound; a++) {
                outs.Write(this.meanReprojError[a]); 
            }
 
            for (int a = 0; a < this.featuresNrFound; a++) {
                outs.Write(this.whitenedError[a]); 
            }
 
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 4; b++) {
                    outs.Write(this.rankValue[a,b]); 
                }
            }
 
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 3; b++) {
                    outs.Write(this.featureLocation[a,b]); 
                }
            }
 
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 9; b++) {
                    outs.Write(this.featureLocationVariances[a,b]); 
                }
            }
 
        }
 
        public triangulation_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public triangulation_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static agile.triangulation_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            agile.triangulation_t o = new agile.triangulation_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.utime = ins.ReadInt64();
 
            this.timestampCamera = ins.ReadInt64();
 
            this.featuresNrFound = ins.ReadInt16();
 
            this.featureId = new short[(int) featuresNrFound];
            for (int a = 0; a < this.featuresNrFound; a++) {
                this.featureId[a] = ins.ReadInt16();
            }
 
            this.numKeys = new short[(int) featuresNrFound];
            for (int a = 0; a < this.featuresNrFound; a++) {
                this.numKeys[a] = ins.ReadInt16();
            }
 
            this.maxReprojError = new double[(int) featuresNrFound];
            for (int a = 0; a < this.featuresNrFound; a++) {
                this.maxReprojError[a] = ins.ReadDouble();
            }
 
            this.meanReprojError = new double[(int) featuresNrFound];
            for (int a = 0; a < this.featuresNrFound; a++) {
                this.meanReprojError[a] = ins.ReadDouble();
            }
 
            this.whitenedError = new double[(int) featuresNrFound];
            for (int a = 0; a < this.featuresNrFound; a++) {
                this.whitenedError[a] = ins.ReadDouble();
            }
 
            this.rankValue = new double[(int) featuresNrFound,(int) 4];
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 4; b++) {
                    this.rankValue[a,b] = ins.ReadDouble();
                }
            }
 
            this.featureLocation = new double[(int) featuresNrFound,(int) 3];
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 3; b++) {
                    this.featureLocation[a,b] = ins.ReadDouble();
                }
            }
 
            this.featureLocationVariances = new double[(int) featuresNrFound,(int) 9];
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 9; b++) {
                    this.featureLocationVariances[a,b] = ins.ReadDouble();
                }
            }
 
        }
 
        public agile.triangulation_t Copy()
        {
            agile.triangulation_t outobj = new agile.triangulation_t();
            outobj.utime = this.utime;
 
            outobj.timestampCamera = this.timestampCamera;
 
            outobj.featuresNrFound = this.featuresNrFound;
 
            outobj.featureId = new short[(int) featuresNrFound];
            for (int a = 0; a < this.featuresNrFound; a++) {
                outobj.featureId[a] = this.featureId[a];
            }
 
            outobj.numKeys = new short[(int) featuresNrFound];
            for (int a = 0; a < this.featuresNrFound; a++) {
                outobj.numKeys[a] = this.numKeys[a];
            }
 
            outobj.maxReprojError = new double[(int) featuresNrFound];
            for (int a = 0; a < this.featuresNrFound; a++) {
                outobj.maxReprojError[a] = this.maxReprojError[a];
            }
 
            outobj.meanReprojError = new double[(int) featuresNrFound];
            for (int a = 0; a < this.featuresNrFound; a++) {
                outobj.meanReprojError[a] = this.meanReprojError[a];
            }
 
            outobj.whitenedError = new double[(int) featuresNrFound];
            for (int a = 0; a < this.featuresNrFound; a++) {
                outobj.whitenedError[a] = this.whitenedError[a];
            }
 
            outobj.rankValue = new double[(int) featuresNrFound,(int) 4];
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 4; b++) {
                    outobj.rankValue[a,b] = this.rankValue[a,b];
                }
            }
 
            outobj.featureLocation = new double[(int) featuresNrFound,(int) 3];
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 3; b++) {
                    outobj.featureLocation[a,b] = this.featureLocation[a,b];
                }
            }
 
            outobj.featureLocationVariances = new double[(int) featuresNrFound,(int) 9];
            for (int a = 0; a < this.featuresNrFound; a++) {
                for (int b = 0; b < 9; b++) {
                    outobj.featureLocationVariances[a,b] = this.featureLocationVariances[a,b];
                }
            }
 
            return outobj;
        }
    }
}

