/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace bot_core
{
    public sealed class raw_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public int length;
        public byte[] data;
 
        public raw_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x182b8da2dc0260c7L;
 
        static raw_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("bot_core.raw_t"))
                return 0L;
 
            classes.Add("bot_core.raw_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.utime); 
 
            outs.Write(this.length); 
 
            for (int a = 0; a < this.length; a++) {
                outs.Write(this.data[a]); 
            }
 
        }
 
        public raw_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public raw_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static bot_core.raw_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            bot_core.raw_t o = new bot_core.raw_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.utime = ins.ReadInt64();
 
            this.length = ins.ReadInt32();
 
            this.data = new byte[(int) length];
            for (int a = 0; a < this.length; a++) {
                this.data[a] = ins.ReadByte();
            }
 
        }
 
        public bot_core.raw_t Copy()
        {
            bot_core.raw_t outobj = new bot_core.raw_t();
            outobj.utime = this.utime;
 
            outobj.length = this.length;
 
            outobj.data = new byte[(int) length];
            for (int a = 0; a < this.length; a++) {
                outobj.data[a] = this.data[a];
            }
 
            return outobj;
        }
    }
}

