/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace agile
{
    public sealed class controlMode_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public short controlMode;
        public long estimChannelIdx;
        public double powerGain;
        public short trajectoryType;
 
        public controlMode_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x13bf441c6c9674afL;
 
        static controlMode_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("agile.controlMode_t"))
                return 0L;
 
            classes.Add("agile.controlMode_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.utime); 
 
            outs.Write(this.controlMode); 
 
            outs.Write(this.estimChannelIdx); 
 
            outs.Write(this.powerGain); 
 
            outs.Write(this.trajectoryType); 
 
        }
 
        public controlMode_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public controlMode_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static agile.controlMode_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            agile.controlMode_t o = new agile.controlMode_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.utime = ins.ReadInt64();
 
            this.controlMode = ins.ReadInt16();
 
            this.estimChannelIdx = ins.ReadInt64();
 
            this.powerGain = ins.ReadDouble();
 
            this.trajectoryType = ins.ReadInt16();
 
        }
 
        public agile.controlMode_t Copy()
        {
            agile.controlMode_t outobj = new agile.controlMode_t();
            outobj.utime = this.utime;
 
            outobj.controlMode = this.controlMode;
 
            outobj.estimChannelIdx = this.estimChannelIdx;
 
            outobj.powerGain = this.powerGain;
 
            outobj.trajectoryType = this.trajectoryType;
 
            return outobj;
        }
    }
}

