/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace agile
{
    public sealed class ekfParams_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public double accelSigmaEKF;
        public double gyroSigmaEKF;
        public double smartNoiseSigmaEKF;
        public double positionSigmaEKF;
        public double orientSigmaEKF;
        public double velocitySigmaEKF;
        public double maxMaxReprojError;
        public double minRankValue;
        public short minNumKeys;
 
        public ekfParams_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x35e75575ddf808cfL;
 
        static ekfParams_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("agile.ekfParams_t"))
                return 0L;
 
            classes.Add("agile.ekfParams_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.utime); 
 
            outs.Write(this.accelSigmaEKF); 
 
            outs.Write(this.gyroSigmaEKF); 
 
            outs.Write(this.smartNoiseSigmaEKF); 
 
            outs.Write(this.positionSigmaEKF); 
 
            outs.Write(this.orientSigmaEKF); 
 
            outs.Write(this.velocitySigmaEKF); 
 
            outs.Write(this.maxMaxReprojError); 
 
            outs.Write(this.minRankValue); 
 
            outs.Write(this.minNumKeys); 
 
        }
 
        public ekfParams_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public ekfParams_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static agile.ekfParams_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            agile.ekfParams_t o = new agile.ekfParams_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.utime = ins.ReadInt64();
 
            this.accelSigmaEKF = ins.ReadDouble();
 
            this.gyroSigmaEKF = ins.ReadDouble();
 
            this.smartNoiseSigmaEKF = ins.ReadDouble();
 
            this.positionSigmaEKF = ins.ReadDouble();
 
            this.orientSigmaEKF = ins.ReadDouble();
 
            this.velocitySigmaEKF = ins.ReadDouble();
 
            this.maxMaxReprojError = ins.ReadDouble();
 
            this.minRankValue = ins.ReadDouble();
 
            this.minNumKeys = ins.ReadInt16();
 
        }
 
        public agile.ekfParams_t Copy()
        {
            agile.ekfParams_t outobj = new agile.ekfParams_t();
            outobj.utime = this.utime;
 
            outobj.accelSigmaEKF = this.accelSigmaEKF;
 
            outobj.gyroSigmaEKF = this.gyroSigmaEKF;
 
            outobj.smartNoiseSigmaEKF = this.smartNoiseSigmaEKF;
 
            outobj.positionSigmaEKF = this.positionSigmaEKF;
 
            outobj.orientSigmaEKF = this.orientSigmaEKF;
 
            outobj.velocitySigmaEKF = this.velocitySigmaEKF;
 
            outobj.maxMaxReprojError = this.maxMaxReprojError;
 
            outobj.minRankValue = this.minRankValue;
 
            outobj.minNumKeys = this.minNumKeys;
 
            return outobj;
        }
    }
}

