/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace agile
{
    public sealed class mesh_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public agile.triangulation_t triangulation;
        public short numPolygons;
        public long[,] indices;
 
        public mesh_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xc91f60be700f6003L;
 
        static mesh_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("agile.mesh_t"))
                return 0L;
 
            classes.Add("agile.mesh_t");
            ulong hash = LCM_FINGERPRINT_BASE
                 + agile.triangulation_t._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.utime); 
 
            this.triangulation._encodeRecursive(outs); 
 
            outs.Write(this.numPolygons); 
 
            for (int a = 0; a < this.numPolygons; a++) {
                for (int b = 0; b < 3; b++) {
                    outs.Write(this.indices[a,b]); 
                }
            }
 
        }
 
        public mesh_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public mesh_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static agile.mesh_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            agile.mesh_t o = new agile.mesh_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.utime = ins.ReadInt64();
 
            this.triangulation = agile.triangulation_t._decodeRecursiveFactory(ins);
 
            this.numPolygons = ins.ReadInt16();
 
            this.indices = new long[(int) numPolygons,(int) 3];
            for (int a = 0; a < this.numPolygons; a++) {
                for (int b = 0; b < 3; b++) {
                    this.indices[a,b] = ins.ReadInt64();
                }
            }
 
        }
 
        public agile.mesh_t Copy()
        {
            agile.mesh_t outobj = new agile.mesh_t();
            outobj.utime = this.utime;
 
            outobj.triangulation = this.triangulation.Copy();
 
            outobj.numPolygons = this.numPolygons;
 
            outobj.indices = new long[(int) numPolygons,(int) 3];
            for (int a = 0; a < this.numPolygons; a++) {
                for (int b = 0; b < 3; b++) {
                    outobj.indices[a,b] = this.indices[a,b];
                }
            }
 
            return outobj;
        }
    }
}

