/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace agile
{
    public sealed class motorsPwms_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public short[] pwms;
 
        public motorsPwms_t()
        {
            pwms = new short[4];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xf7a14890fd8f8265L;
 
        static motorsPwms_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("agile.motorsPwms_t"))
                return 0L;
 
            classes.Add("agile.motorsPwms_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.utime); 
 
            for (int a = 0; a < 4; a++) {
                outs.Write(this.pwms[a]); 
            }
 
        }
 
        public motorsPwms_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public motorsPwms_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static agile.motorsPwms_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            agile.motorsPwms_t o = new agile.motorsPwms_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.utime = ins.ReadInt64();
 
            this.pwms = new short[(int) 4];
            for (int a = 0; a < 4; a++) {
                this.pwms[a] = ins.ReadInt16();
            }
 
        }
 
        public agile.motorsPwms_t Copy()
        {
            agile.motorsPwms_t outobj = new agile.motorsPwms_t();
            outobj.utime = this.utime;
 
            outobj.pwms = new short[(int) 4];
            for (int a = 0; a < 4; a++) {
                outobj.pwms[a] = this.pwms[a];
            }
 
            return outobj;
        }
    }
}

