/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace agile
{
    public sealed class networkCheck_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public String channel;
        public short numStamps;
        public long[] timestampOrigin;
        public long timestampReceived;
 
        public networkCheck_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xb161f9f021c66c66L;
 
        static networkCheck_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("agile.networkCheck_t"))
                return 0L;
 
            classes.Add("agile.networkCheck_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            outs.Write(this.utime); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.channel); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            outs.Write(this.numStamps); 
 
            for (int a = 0; a < this.numStamps; a++) {
                outs.Write(this.timestampOrigin[a]); 
            }
 
            outs.Write(this.timestampReceived); 
 
        }
 
        public networkCheck_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public networkCheck_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static agile.networkCheck_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            agile.networkCheck_t o = new agile.networkCheck_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.utime = ins.ReadInt64();
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.channel = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.numStamps = ins.ReadInt16();
 
            this.timestampOrigin = new long[(int) numStamps];
            for (int a = 0; a < this.numStamps; a++) {
                this.timestampOrigin[a] = ins.ReadInt64();
            }
 
            this.timestampReceived = ins.ReadInt64();
 
        }
 
        public agile.networkCheck_t Copy()
        {
            agile.networkCheck_t outobj = new agile.networkCheck_t();
            outobj.utime = this.utime;
 
            outobj.channel = this.channel;
 
            outobj.numStamps = this.numStamps;
 
            outobj.timestampOrigin = new long[(int) numStamps];
            for (int a = 0; a < this.numStamps; a++) {
                outobj.timestampOrigin[a] = this.timestampOrigin[a];
            }
 
            outobj.timestampReceived = this.timestampReceived;
 
            return outobj;
        }
    }
}

