/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace agile
{
    public sealed class stateVariances_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public long timestampDevice;
        public double[] position;
        public double[] orient;
        public double[] veloPositionBody;
        public double[] veloOrientBody;
        public double[] imuBiasAccel;
        public double[] imuBiasGyro;
        public double[] imuVarianceAccel;
        public double[] imuVarianceGyro;
        public double[,] variances;
        public long deltaSensAcquiToEstimPub;
 
        public stateVariances_t()
        {
            position = new double[3];
            orient = new double[4];
            veloPositionBody = new double[3];
            veloOrientBody = new double[3];
            imuBiasAccel = new double[3];
            imuBiasGyro = new double[3];
            imuVarianceAccel = new double[3];
            imuVarianceGyro = new double[3];
            variances = new double[12,12];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x05c915ae3cc8ed1bL;
 
        static stateVariances_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("agile.stateVariances_t"))
                return 0L;
 
            classes.Add("agile.stateVariances_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.utime); 
 
            outs.Write(this.timestampDevice); 
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.position[a]); 
            }
 
            for (int a = 0; a < 4; a++) {
                outs.Write(this.orient[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.veloPositionBody[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.veloOrientBody[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.imuBiasAccel[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.imuBiasGyro[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.imuVarianceAccel[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.imuVarianceGyro[a]); 
            }
 
            for (int a = 0; a < 12; a++) {
                for (int b = 0; b < 12; b++) {
                    outs.Write(this.variances[a,b]); 
                }
            }
 
            outs.Write(this.deltaSensAcquiToEstimPub); 
 
        }
 
        public stateVariances_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public stateVariances_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static agile.stateVariances_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            agile.stateVariances_t o = new agile.stateVariances_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.utime = ins.ReadInt64();
 
            this.timestampDevice = ins.ReadInt64();
 
            this.position = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.position[a] = ins.ReadDouble();
            }
 
            this.orient = new double[(int) 4];
            for (int a = 0; a < 4; a++) {
                this.orient[a] = ins.ReadDouble();
            }
 
            this.veloPositionBody = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.veloPositionBody[a] = ins.ReadDouble();
            }
 
            this.veloOrientBody = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.veloOrientBody[a] = ins.ReadDouble();
            }
 
            this.imuBiasAccel = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.imuBiasAccel[a] = ins.ReadDouble();
            }
 
            this.imuBiasGyro = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.imuBiasGyro[a] = ins.ReadDouble();
            }
 
            this.imuVarianceAccel = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.imuVarianceAccel[a] = ins.ReadDouble();
            }
 
            this.imuVarianceGyro = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.imuVarianceGyro[a] = ins.ReadDouble();
            }
 
            this.variances = new double[(int) 12,(int) 12];
            for (int a = 0; a < 12; a++) {
                for (int b = 0; b < 12; b++) {
                    this.variances[a,b] = ins.ReadDouble();
                }
            }
 
            this.deltaSensAcquiToEstimPub = ins.ReadInt64();
 
        }
 
        public agile.stateVariances_t Copy()
        {
            agile.stateVariances_t outobj = new agile.stateVariances_t();
            outobj.utime = this.utime;
 
            outobj.timestampDevice = this.timestampDevice;
 
            outobj.position = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.position[a] = this.position[a];
            }
 
            outobj.orient = new double[(int) 4];
            for (int a = 0; a < 4; a++) {
                outobj.orient[a] = this.orient[a];
            }
 
            outobj.veloPositionBody = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.veloPositionBody[a] = this.veloPositionBody[a];
            }
 
            outobj.veloOrientBody = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.veloOrientBody[a] = this.veloOrientBody[a];
            }
 
            outobj.imuBiasAccel = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.imuBiasAccel[a] = this.imuBiasAccel[a];
            }
 
            outobj.imuBiasGyro = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.imuBiasGyro[a] = this.imuBiasGyro[a];
            }
 
            outobj.imuVarianceAccel = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.imuVarianceAccel[a] = this.imuVarianceAccel[a];
            }
 
            outobj.imuVarianceGyro = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.imuVarianceGyro[a] = this.imuVarianceGyro[a];
            }
 
            outobj.variances = new double[(int) 12,(int) 12];
            for (int a = 0; a < 12; a++) {
                for (int b = 0; b < 12; b++) {
                    outobj.variances[a,b] = this.variances[a,b];
                }
            }
 
            outobj.deltaSensAcquiToEstimPub = this.deltaSensAcquiToEstimPub;
 
            return outobj;
        }
    }
}

