/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace agile
{
    public sealed class statusDrone_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public short status;
 
        public statusDrone_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xedc526712f80f74fL;
 
        static statusDrone_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("agile.statusDrone_t"))
                return 0L;
 
            classes.Add("agile.statusDrone_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.utime); 
 
            outs.Write(this.status); 
 
        }
 
        public statusDrone_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public statusDrone_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static agile.statusDrone_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            agile.statusDrone_t o = new agile.statusDrone_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.utime = ins.ReadInt64();
 
            this.status = ins.ReadInt16();
 
        }
 
        public agile.statusDrone_t Copy()
        {
            agile.statusDrone_t outobj = new agile.statusDrone_t();
            outobj.utime = this.utime;
 
            outobj.status = this.status;
 
            return outobj;
        }
    }
}

