/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace bot_core
{
    public sealed class image_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public int width;
        public int height;
        public int row_stride;
        public int pixelformat;
        public int size;
        public byte[] data;
        public int nmetadata;
        public bot_core.image_metadata_t[] metadata;
 
        public image_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x6fee6cb20472ff6aL;
 
        public const int PIXEL_FORMAT_UYVY = 1498831189;
        public const int PIXEL_FORMAT_YUYV = 1448695129;
        public const int PIXEL_FORMAT_IYU1 = 827677001;
        public const int PIXEL_FORMAT_IYU2 = 844454217;
        public const int PIXEL_FORMAT_YUV420 = 842093913;
        public const int PIXEL_FORMAT_YUV411P = 1345401140;
        public const int PIXEL_FORMAT_I420 = 808596553;
        public const int PIXEL_FORMAT_NV12 = 842094158;
        public const int PIXEL_FORMAT_GRAY = 1497715271;
        public const int PIXEL_FORMAT_RGB = 859981650;
        public const int PIXEL_FORMAT_BGR = 861030210;
        public const int PIXEL_FORMAT_RGBA = 876758866;
        public const int PIXEL_FORMAT_BGRA = 877807426;
        public const int PIXEL_FORMAT_BAYER_BGGR = 825770306;
        public const int PIXEL_FORMAT_BAYER_GBRG = 844650584;
        public const int PIXEL_FORMAT_BAYER_GRBG = 861427800;
        public const int PIXEL_FORMAT_BAYER_RGGB = 878205016;
        public const int PIXEL_FORMAT_BE_BAYER16_BGGR = 826360386;
        public const int PIXEL_FORMAT_BE_BAYER16_GBRG = 843137602;
        public const int PIXEL_FORMAT_BE_BAYER16_GRBG = 859914818;
        public const int PIXEL_FORMAT_BE_BAYER16_RGGB = 876692034;
        public const int PIXEL_FORMAT_LE_BAYER16_BGGR = 826360396;
        public const int PIXEL_FORMAT_LE_BAYER16_GBRG = 843137612;
        public const int PIXEL_FORMAT_LE_BAYER16_GRBG = 859914828;
        public const int PIXEL_FORMAT_LE_BAYER16_RGGB = 876692044;
        public const int PIXEL_FORMAT_MJPEG = 1196444237;
        public const int PIXEL_FORMAT_SNAPPY_GRAY = 1863245895;
        public const int PIXEL_FORMAT_BE_GRAY16 = 357;
        public const int PIXEL_FORMAT_LE_GRAY16 = 909199180;
        public const int PIXEL_FORMAT_BE_RGB16 = 358;
        public const int PIXEL_FORMAT_LE_RGB16 = 1279412050;
        public const int PIXEL_FORMAT_BE_SIGNED_GRAY16 = 359;
        public const int PIXEL_FORMAT_BE_SIGNED_RGB16 = 360;
        public const int PIXEL_FORMAT_FLOAT_GRAY32 = 842221382;
        public const int PIXEL_FORMAT_INVALID = -2;
        public const int PIXEL_FORMAT_ANY = -1;

        static image_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("bot_core.image_t"))
                return 0L;
 
            classes.Add("bot_core.image_t");
            ulong hash = LCM_FINGERPRINT_BASE
                 + bot_core.image_metadata_t._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.utime); 
 
            outs.Write(this.width); 
 
            outs.Write(this.height); 
 
            outs.Write(this.row_stride); 
 
            outs.Write(this.pixelformat); 
 
            outs.Write(this.size); 
 
            for (int a = 0; a < this.size; a++) {
                outs.Write(this.data[a]); 
            }
 
            outs.Write(this.nmetadata); 
 
            for (int a = 0; a < this.nmetadata; a++) {
                this.metadata[a]._encodeRecursive(outs); 
            }
 
        }
 
        public image_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public image_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static bot_core.image_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            bot_core.image_t o = new bot_core.image_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.utime = ins.ReadInt64();
 
            this.width = ins.ReadInt32();
 
            this.height = ins.ReadInt32();
 
            this.row_stride = ins.ReadInt32();
 
            this.pixelformat = ins.ReadInt32();
 
            this.size = ins.ReadInt32();
 
            this.data = new byte[(int) size];
            for (int a = 0; a < this.size; a++) {
                this.data[a] = ins.ReadByte();
            }
 
            this.nmetadata = ins.ReadInt32();
 
            this.metadata = new bot_core.image_metadata_t[(int) nmetadata];
            for (int a = 0; a < this.nmetadata; a++) {
                this.metadata[a] = bot_core.image_metadata_t._decodeRecursiveFactory(ins);
            }
 
        }
 
        public bot_core.image_t Copy()
        {
            bot_core.image_t outobj = new bot_core.image_t();
            outobj.utime = this.utime;
 
            outobj.width = this.width;
 
            outobj.height = this.height;
 
            outobj.row_stride = this.row_stride;
 
            outobj.pixelformat = this.pixelformat;
 
            outobj.size = this.size;
 
            outobj.data = new byte[(int) size];
            for (int a = 0; a < this.size; a++) {
                outobj.data[a] = this.data[a];
            }
 
            outobj.nmetadata = this.nmetadata;
 
            outobj.metadata = new bot_core.image_metadata_t[(int) nmetadata];
            for (int a = 0; a < this.nmetadata; a++) {
                outobj.metadata[a] = this.metadata[a].Copy();
            }
 
            return outobj;
        }
    }
}

