/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace bot_core
{
    public sealed class rigid_transform_t : LCM.LCM.LCMEncodable
    {
        public long utime;
        public double[] trans;
        public double[] quat;
 
        public rigid_transform_t()
        {
            trans = new double[3];
            quat = new double[4];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x754ffdf95662e2d7L;
 
        static rigid_transform_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("bot_core.rigid_transform_t"))
                return 0L;
 
            classes.Add("bot_core.rigid_transform_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.utime); 
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.trans[a]); 
            }
 
            for (int a = 0; a < 4; a++) {
                outs.Write(this.quat[a]); 
            }
 
        }
 
        public rigid_transform_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public rigid_transform_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static bot_core.rigid_transform_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            bot_core.rigid_transform_t o = new bot_core.rigid_transform_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.utime = ins.ReadInt64();
 
            this.trans = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.trans[a] = ins.ReadDouble();
            }
 
            this.quat = new double[(int) 4];
            for (int a = 0; a < 4; a++) {
                this.quat[a] = ins.ReadDouble();
            }
 
        }
 
        public bot_core.rigid_transform_t Copy()
        {
            bot_core.rigid_transform_t outobj = new bot_core.rigid_transform_t();
            outobj.utime = this.utime;
 
            outobj.trans = new double[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.trans[a] = this.trans[a];
            }
 
            outobj.quat = new double[(int) 4];
            for (int a = 0; a < 4; a++) {
                outobj.quat[a] = this.quat[a];
            }
 
            return outobj;
        }
    }
}

